"""empty message

Revision ID: 357fba699a6f
Revises: 09b914c124f2
Create Date: 2024-06-19 20:01:25.733773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '357fba699a6f'
down_revision = '09b914c124f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influencer', schema=None) as batch_op:
        batch_op.alter_column('er_instagram',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('seguidores_instagram',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('er_tiktok',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('seguidores_tiktok',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('imagen',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('estilo_de_vida',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influencer', schema=None) as batch_op:
        batch_op.alter_column('estilo_de_vida',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('imagen',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('seguidores_tiktok',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('er_tiktok',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('seguidores_instagram',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('er_instagram',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###
