"""empty message

Revision ID: a852839408e5
Revises: 357fba699a6f
Create Date: 2024-06-28 06:47:55.942108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a852839408e5'
down_revision = '357fba699a6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('propuesta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lista_influencers_table',
    sa.Column('lista_id', sa.Integer(), nullable=False),
    sa.Column('influencer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencer.id'], ),
    sa.ForeignKeyConstraint(['lista_id'], ['lista.id'], ),
    sa.PrimaryKeyConstraint('lista_id', 'influencer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lista_influencers_table')
    op.drop_table('propuesta')
    op.drop_table('lista')
    # ### end Alembic commands ###
