"""empty message

Revision ID: fa2bf84841a5
Revises: b1528c38253a
Create Date: 2024-07-03 02:09:14.776276

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fa2bf84841a5'
down_revision = 'b1528c38253a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influencer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instagram_user', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tiktok_user', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=9), nullable=True))
        batch_op.alter_column('red_social',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('er_instagram',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('seguidores_instagram',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('er_tiktok',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('seguidores_tiktok',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('imagen',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('estilo_de_vida',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('sexo',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influencer', schema=None) as batch_op:
        batch_op.alter_column('sexo',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('estilo_de_vida',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('imagen',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('seguidores_tiktok',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('er_tiktok',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('seguidores_instagram',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('er_instagram',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('red_social',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('tiktok_user')
        batch_op.drop_column('instagram_user')

    # ### end Alembic commands ###
