
POST https://cautious-palm-tree-qjp54vp76gwfqwp-3001.app.github.dev/api/auth/register
Content-Type: application/json

{
    "email": "12345@hans.com",
    "password": "12345"
}

### GET 



GET https://zany-disco-q7q67jgv5jgf4rq9-3001.app.github.dev/api/auth/


### Login

POST https://zany-disco-q7q67jgv5jgf4rq9-3001.app.github.dev/api/auth/login
Content-Type: application/json


{
    "email": "1234@hola.com",
    "password": "1234"
}

### Modify Password

PUT https://zany-disco-q7q67jgv5jgf4rq9-3001.app.github.dev/api/auth/change-password
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "password": "1234"
}